version: 2
updates:
  # Enable version updates for Gradle
  - package-ecosystem: "gradle"
    # Look for `build.gradle` file in the `root` directory
    directory: "/"
    # Check for updates every day (weekdays)
    schedule:
      interval: "daily"
    allow:
      # Allow updates for Exactpro packages
      - dependency-name: "com.exactpro*"
    # Allow up to 10 open pull requests
    open-pull-requests-limit: 10
