name: "Run integration tests for common"

on:
  push:
    branches:
      - '*'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 'zulu' '11'
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        run: ./gradlew --info integrationTest
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: integration-test-results
          path: build/reports/tests/integrationTest/
